apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: azure-friday-shipments-scaler
spec:
  scaleTargetRef:
    name: azure-friday-shipments
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: shipments
      messageCount: '5'
    authenticationRef:
      name: azure-friday-trigger-auth