apiVersion: v1
kind: Secret
metadata:
  name: azure-friday-secrets-autoscaler
  labels:
    app: azure-friday-orders
data:
  servicebus-management-connectionstring: <base64-encoded-connection-string-with-manage-permissions>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-friday-trigger-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: azure-friday-secrets-autoscaler
    key: servicebus-management-connectionstring
---
apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: azure-friday-orders-scaler
spec:
  scaleTargetRef:
    name: azure-friday-orders
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: orders
      messageCount: '5'
    authenticationRef:
      name: azure-friday-trigger-auth