name: CI
on:
  - pull_request

jobs:
  solution:
    name: Solution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: dotnet build ./src/AzureFriday.sln
  orders:
    name: Orders (Docker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build ./src/ --file ./src/AzureFriday.Orders/Dockerfile
  shipments:
    name: Shipments (Docker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build ./src/ --file ./src/AzureFriday.Shipments/Dockerfile
