name: Push Docker Images
on:
  push:
    branches: [ main ]

jobs:
  shipments:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: tomkerkhove
        password: ${{ secrets.CONTAINER_REGISTRY_KEY }}
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/AzureFriday.Shipments/Dockerfile --tag ghcr.io/tomkerkhove/azure-friday-shipments:latest
    - name: Push the Docker image
      run: docker push ghcr.io/tomkerkhove/azure-friday-shipments:latest
  orders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        registry: ghcr.io
        username: tomkerkhove
        password: ${{ secrets.CONTAINER_REGISTRY_KEY }}
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/AzureFriday.Orders/Dockerfile --tag ghcr.io/tomkerkhove/azure-friday-orders:latest
    - name: Push the Docker image
      run: docker push ghcr.io/tomkerkhove/azure-friday-orders:latest